# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('value', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(editable=False, max_length=140, unique=True)),
                ('type', models.CharField(choices=[('NN', 'Noun'), ('ADJ', 'Adjective'), ('ADV', 'Adverb'), ('V', 'Verb')], max_length=5, null=True)),
                ('last_tweet_id', models.CharField(default='0', editable=False, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='WordUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retweets', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle_app.Word')),
            ],
        ),
        migrations.AddField(
            model_name='synonym',
            name='synonym_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='synonym_to_word', to='battle_app.Word'),
        ),
        migrations.AddField(
            model_name='synonym',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle_app.Word'),
        ),
        migrations.AlterUniqueTogether(
            name='synonym',
            unique_together=set([('synonym_to', 'word')]),
        ),
    ]
