# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('battle_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='word',
            name='last_tweet_id',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
