# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_app', '0003_auto_20160915_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_type',
            field=models.CharField(choices=[('NN', 'Noun'), ('ADJ', 'Adjective'), ('ADV', 'Adverb'), ('VB', 'Verb')], max_length=5, null=True),
        ),
    ]
