# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_app', '0004_auto_20160915_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_type',
            field=models.CharField(choices=[('NN', 'noun, common, singular or mass'), ('NNS', 'noun, common, plural'), ('RB', 'adverb'), ('RBR', 'adverb, comparative'), ('RBS', 'adverb, superlative'), ('JJ', 'adjective or numeral, ordinal'), ('JJR', 'adjective, comparative'), ('JJS', 'adjective, superlative'), ('VB', 'verb, base form')], max_length=5, null=True),
        ),
    ]
